name: Run Name Demo

run-name: "Run Name Demo by@${{ github.actor }} No${{ github.run_number }}"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Print run information
        run: |
          echo "Run Name: ${{ github.run_name }}" && echo "Run Name: $GITHUB_RUN_NAME"
